eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liuhuilove/testGit.git
          searchPaths: spring-cloud/helloworldConfig
  application:
    name: config-server
    
  rabbitmq:
    host: 192.168.100.128
    port: 5672
    username: root
    password: root
    