server:
  port: 8902
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  application:
    name: feign
   
feign:
  hystrix:
    enabled: true
    