eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
server:
  port: 8904
  
spring:
  application:
    name: zuul
    
zuul:
  routes:
    ribbon:
      path: /api-ribbon/**
      service-id: ribbon
    feign:
      path: /api-feign/**
      service-id: feign
      